### ISSUE TITLE
VSCode default themes

### ISSUE THREAD

**Issue by devondahon** [lysyi3m/macos-terminal-themes#45]
Could we also have **VSCode** default themes : **Light+** and **Dark+** ?

**Comment by lysyi3m** [comment]
@devondahon sure.

[Dark+](https://github.com/lysyi3m/macos-terminal-themes#vs-code-dark-plus-download)

![](https://github.com/lysyi3m/macos-terminal-themes/blob/master/screenshots/vs_code_dark_plus.png?raw=true)

[Light+](https://github.com/lysyi3m/macos-terminal-themes#vs-code-light-plus-download)

![](https://github.com/lysyi3m/macos-terminal-themes/blob/master/screenshots/vs_code_light_plus.png?raw=true)
