### ISSUE TITLE
everyday or weekly auto-change theme

### ISSUE THREAD

**Issue by ddpopbb3** [lysyi3m/macos-terminal-themes#55]
Sooooo many cooool themes , I wanna to use each of them in my terminal
Could you please provide a option to auto-change theme everyday or weekly?

**Comment by lysyi3m** [comment]
Thank you.

Unfortunately, no. This repo is for themes and themes only. Since Terminal.app has no such functionality out the box, you have to implement this manually using shell scripts with crontab or Automator scripts - based on your setup and environment.
